name: data_eng_assignment
profile: data_eng_assignment
model-paths: ["models"]
version: "1.0"

models:
  my_dbt_project:
    +materialized: table
    marts:
      +post-hook:
        - "copy (select * from {{ this }}) to '/opt/airflow/data/parquet/{{ this.name }}.parquet' (format parquet);"
